'use strict';

var base_url = 'http://helm1/';
var auth = "Basic ZG86ZG8=";

//var base_url = 'https://www.dbunic.cnrs-gif.fr/visiondb/';
//var auth = "Basic YW50b2xpa2phbjphamFu";

/* Services */

angular.module( 'notebookServices', ['ngResource'] )

    // configurations valid for all requests
    .config( ['$httpProvider', function( $httpProvider )
        {
            $httpProvider.defaults.headers.common['Authorization'] = auth;
        }
    ])

    .factory( 'Experiment', 
        function( $resource ){ // , $filter can be added if ngFilter is injected above
            return $resource(
                base_url + 'experiment/:id', 
                { 
                    id:'@eId', 
                    callback: 'JSON_CALLBACK' // automatic callback function generated by angularjs
                }, 
                { 
                    query: { method: 'JSONP', params:{format:'jsonp'}, isArray: false, headers:{Authorization:auth} }
                }
            );
        }
    )

;
